/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"

// GetCondition of this NopResource.
func (mg *NopResource) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this NopResource.
func (mg *NopResource) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.Crossplane.ManagementPolicies
}

// GetProviderConfigReference of this NopResource.
func (mg *NopResource) GetProviderConfigReference() *xpv1.Reference {
	return mg.Spec.Crossplane.ProviderConfigReference
}

// GetPublishConnectionDetailsTo of this NopResource.
func (mg *NopResource) GetPublishConnectionDetailsTo() *xpv1.PublishConnectionDetailsTo {
	return mg.Spec.Crossplane.PublishConnectionDetailsTo
}

// SetConditions of this NopResource.
func (mg *NopResource) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this NopResource.
func (mg *NopResource) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.Crossplane.ManagementPolicies = r
}

// SetProviderConfigReference of this NopResource.
func (mg *NopResource) SetProviderConfigReference(r *xpv1.Reference) {
	mg.Spec.Crossplane.ProviderConfigReference = r
}

// SetPublishConnectionDetailsTo of this NopResource.
func (mg *NopResource) SetPublishConnectionDetailsTo(r *xpv1.PublishConnectionDetailsTo) {
	mg.Spec.Crossplane.PublishConnectionDetailsTo = r
}
